"""create matakuliah

Revision ID: 824cac124150
Revises: 797d16e8f700
Create Date: 2025-05-13 19:45:09.362643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '824cac124150'
down_revision = '797d16e8f700'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
